# Generated by Django 5.0.6 on 2024-06-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanfic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fanfic',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='fanfic',
            name='tags',
        ),
        migrations.AddField(
            model_name='fanfic',
            name='content',
            field=models.TextField(default='Текст фанфика будет здесь.'),
        ),
        migrations.AddField(
            model_name='fanfic',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='fanfic_images/'),
        ),
        migrations.AddField(
            model_name='fanfic',
            name='rating',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
