# Generated by Django 5.0.6 on 2024-06-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanfic', '0002_remove_fanfic_created_at_remove_fanfic_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fanfic',
            name='tags',
            field=models.TextField(default='Гарем, Юри'),
        ),
    ]
