# Generated by Django 5.0.6 on 2024-06-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanfic', '0003_fanfic_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fanfic',
            name='description',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='fanfic',
            name='tags',
            field=models.CharField(default='Гарем, Юри', max_length=400),
        ),
    ]
