# Generated by Django 5.0.6 on 2024-06-24 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanfic', '0004_alter_fanfic_description_alter_fanfic_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('fanfic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='fanfic.fanfic')),
            ],
        ),
    ]
